import * as antUtils from '@antv/util';
import * as Annotation from './components/Annotation';
import * as G2 from './g2-all';
import * as GComponents from './g-components';
import * as bxUtil from './utils';
export declare const Util: {
    getLegendItems: typeof import("@antv/g2/lib/util/legend").getLegendItems;
    translate: typeof import("@antv/g2/lib/util/transform").translate;
    rotate: typeof import("@antv/g2/lib/util/transform").rotate;
    zoom: typeof import("@antv/g2/lib/util/transform").zoom;
    transform: (m: number[], actions: any[][]) => number[];
    getAngle: typeof import("@antv/g2/lib/util/graphics").getAngle;
    getSectorPath: typeof import("@antv/g2/lib/util/graphics").getSectorPath;
    polarToCartesian: typeof import("@antv/g2/lib/util/graphics").polarToCartesian;
    getDelegationObject: typeof import("@antv/g2/lib/interaction/action/util").getDelegationObject;
    getTooltipItems: typeof import("@antv/g2/lib/util/tooltip").getTooltipItems;
    fold: (data: any[], fields: string[], foldCate: string, foldValue: string) => any[];
    percentage: (data: object[], field: string, as: string, groupBy?: string | string[]) => any[];
    minifyNum: (num: any, decimal?: number) => any;
    splitBySeparator: (num: any, separator?: string) => any;
    visibleHelper: (cfg: any, defaultVisible?: boolean) => {
        visible: boolean;
        text: string | import("react").ReactElement<unknown, string | import("react").JSXElementConstructor<any>>;
    } | {
        visible: boolean;
        text?: undefined;
    };
    cloneDeep: (deepObject: any) => any;
    shallowEqual: typeof bxUtil.shallowEqual;
    contains: (arr: any[], value: any) => boolean;
    includes: (arr: any[], value: any) => boolean;
    difference: <T>(arr: T[], values?: T[]) => T[];
    find: typeof antUtils.find;
    findIndex: typeof antUtils.findIndex;
    firstValue: (data: object[], name: string) => any;
    flatten: <T>(arr: T[]) => T[];
    flattenDeep: (arr: any[], result?: any[]) => any[];
    getRange: (values: number[]) => import("@antv/util/lib/get-range").RangeType;
    pull: <T>(arr: T[], ...values: any[]) => T[];
    pullAt: <T>(arr: T[], indexes: number[]) => T[];
    reduce: <T, G>(arr: import("@antv/util/lib/types").ObjectType<T> | G[], fn: (result: T, data: G, idx: string | number) => T, init: T) => T;
    remove: <T>(arr: T[], predicate: (value: T, idx: number, arr?: T[]) => boolean) => T[];
    sortBy: typeof antUtils.sortBy;
    union: (...sources: any[]) => any[];
    uniq: typeof antUtils.uniq;
    valuesOfKey: (data: any[], name: string) => any[];
    head: typeof antUtils.head;
    last: typeof antUtils.last;
    startsWith: typeof antUtils.startsWith;
    endsWith: typeof antUtils.endsWith;
    filter: <T>(arr: T[], func: (v: T, idx: number) => boolean) => T[];
    every: <T>(arr: T[], func: (v: T, idx?: number) => any) => boolean;
    some: <T>(arr: T[], func: (v: T, idx?: number) => any) => boolean;
    group: <T>(data: T[], condition: string | string[] | ((v: T) => string)) => T[][];
    groupBy: typeof antUtils.groupBy;
    groupToMap: typeof antUtils.groupToMap;
    getWrapBehavior: typeof antUtils.getWrapBehavior;
    wrapBehavior: typeof antUtils.wrapBehavior;
    number2color: typeof antUtils.number2color;
    parseRadius: typeof antUtils.parseRadius;
    clamp: (a: number, min: number, max: number) => number;
    fixedBase: (v: number, base: number | string) => number;
    isDecimal: (num: any) => boolean;
    isEven: (num: any) => boolean;
    isInteger: (number: unknown) => boolean;
    isNegative: (num: any) => boolean;
    isNumberEqual: typeof antUtils.isNumberEqual;
    isOdd: (num: any) => boolean;
    isPositive: (num: any) => boolean;
    max: (arr: number[]) => number | undefined;
    maxBy: <T>(arr: T[], fn: string | ((v: T) => number)) => T;
    min: (arr: number[]) => number | undefined;
    minBy: <T>(arr: T[], fn: string | ((v: T) => number)) => T;
    mod: (n: number, m: number) => number;
    toDegree: (radian: number) => number;
    toInteger: typeof antUtils.toInteger;
    toRadian: (degree: number) => number;
    forIn: typeof antUtils.forIn;
    has: (obj: object, key: any) => boolean;
    hasKey: (obj: object, key: any) => boolean;
    hasValue: (obj: object, value: any) => boolean;
    keys: (obj: any) => any[];
    isMatch: typeof antUtils.isMatch;
    values: (obj: any) => any;
    lowerCase: (str: string) => string;
    lowerFirst: (value: string) => string;
    substitute: typeof antUtils.substitute;
    upperCase: (str: string) => string;
    upperFirst: (value: string) => string;
    getType: (value: any) => string;
    isArguments: (value: any) => boolean;
    isArray: (value: any) => value is any[];
    isArrayLike: (value: any) => boolean;
    isBoolean: (value: any) => value is boolean;
    isDate: (value: any) => value is Date;
    isError: (value: any) => value is Error;
    isFunction: (value: any) => value is Function;
    isFinite: typeof antUtils.isFinite;
    isNil: (value: any) => value is null;
    isNull: (value: any) => value is null;
    isNumber: (value: any) => value is number;
    isObject: <T = object>(value: any) => value is T;
    isObjectLike: (value: any) => value is object;
    isPlainObject: (value: any) => value is object;
    isPrototype: (value: any) => boolean;
    isRegExp: (str: any) => str is RegExp;
    isString: (str: any) => str is string;
    isType: (value: any, type: string) => boolean;
    isUndefined: (value: any) => value is undefined;
    isElement: (o: any) => boolean;
    requestAnimationFrame: typeof antUtils.requestAnimationFrame;
    clearAnimationFrame: typeof antUtils.clearAnimationFrame;
    augment: (...args: any[]) => void;
    clone: (obj: any) => any;
    debounce: typeof antUtils.debounce;
    memoize: (f: Function, resolver?: (...args: any[]) => string) => {
        (...args: any[]): any;
        cache: Map<any, any>;
    };
    deepMix: (rst: any, ...args: any[]) => any;
    each: typeof antUtils.forIn;
    extend: (subclass: any, superclass: any, overrides?: any, staticOverrides?: any) => any;
    indexOf: <T>(arr: T[], obj: T) => number;
    isEmpty: typeof antUtils.isEmpty;
    isEqual: (value: any, other: any) => boolean;
    isEqualWith: <T>(value: T, other: T, fn: (v1: T, v2: T) => boolean) => boolean;
    map: <T, G>(arr: T[], func: (v: T, idx: number) => G) => G[];
    mapValues: <T>(object: {
        [key: string]: T;
    }, func?: (value: T, key: string) => any) => {
        [key: string]: any;
    };
    mix: typeof antUtils.mix;
    assign: typeof antUtils.mix;
    get: (obj: any, key: string | any[], defaultValue?: any) => any;
    set: (obj: any, path: string | any[], value: any) => any;
    pick: <T>(object: import("@antv/util/lib/pick").ObjectType<T>, keys: string[]) => import("@antv/util/lib/pick").ObjectType<T>;
    omit: <T>(obj: import("@antv/util/lib/types").ObjectType<T>, keys: string[]) => import("@antv/util/lib/types").ObjectType<T>;
    throttle: (func: Function, wait: number, options: import("@antv/util/lib/throttle").OptionsType) => Function;
    toArray: (value: any) => any[];
    toString: (value: any) => string;
    uniqueId: (prefix?: string) => string;
    noop: () => void;
    identity: <T>(v: T) => T;
    size: typeof antUtils.size;
    Cache: typeof antUtils.Cache;
};
export { Annotation, G2, GComponents };
export { default as Chart } from './components/Chart';
export { default as View } from './components/View';
export { default as Tooltip } from './components/Tooltip';
export { default as Legend } from './components/Legend';
export { default as Coordinate } from './components/Coordinate';
export { default as Axis } from './components/Axis';
export { default as Facet } from './components/Facet';
export { default as Slider } from './components/Slider';
export { default as Area } from './geometry/Area';
export { default as Edge } from './geometry/Edge';
export { default as Heatmap } from './geometry/Heatmap';
export { default as Interval } from './geometry/Interval';
export { default as Line } from './geometry/Line';
export { default as Point } from './geometry/Point';
export { default as Polygon } from './geometry/Polygon';
export { default as Schema } from './geometry/Schema';
export { default as BaseGeom } from './geometry/Base';
export { default as Label } from './geometry/Label';
export { default as Path } from './geometry/Path';
export { default as LineAdvance } from './geometry/LineAdvance';
export { default as Geom } from './geometry';
export { default as Coord } from './components/Coordinate/coord';
export { default as Guide } from './adapter/Guide';
export { default as Effects } from './components/Effects';
export { default as Interaction } from './components/Interaction';
export { default as createPlot } from './createPlot';
export { default as createTooltipConnector } from './connector/createTooltipConnector';
export { default as useView } from './hooks/useChartView';
export { default as useRootChart } from './hooks/useChartInstance';
export { default as useChartInstance } from './hooks/useChartInstance';
export { default as useTheme } from './hooks/useTheme';
export { withView } from './context/view';
export { withChartInstance } from './context/root';
export * from './core';
export * from './plots';
